### ISSUE TITLE
Engine off gestion

### ISSUE THREAD

**Issue by fluuxxxx** [overextended/ox_fuel#102]
Hey, would be cool if the fuel level stop decrease when you are in a vehicle that has the engine turned off. I tried to do it my-self but it decrease while you are in a vehicle in the driver seat.. thank you so much and thanks for the open source scripts love u <3

More infos (sorry for my bad english) : 

I've tried to add a func to check if the vehicle engine is running in the startDrivingVehicle func, but it seems like the GetVehicleFuelLevel func of fivem return a different fuel level as Entity(vehicle).state.fuel (maybe GTA by default when the consumption is turned on it will consume if you are in the driver seat no matter if the engine is running)

Edit : 

My bad i was missing something... sooo that how i do it : 

I add `if not IsVehicleEngineOn(vehicle) then return end` in the while loop of startDrivingVehicle func right after `if not DoesEntityExist(vehicle) then return end` then when I start the engine i also do `if cache.seat == -1 then CreateThread(startDrivingVehicle) end`

Really simple I'm tired sorry but I leave the issue here so if someone want to implement it : )

Don't know if it's a nice way to do it but honestly that work ^^

**Comment by thelindat** [comment]
I'm using the native fuel system, so turning the engine off already does stop fuel consumption - unless the fuel tank is damaged which means it will leak (might need tweaking).
