### ISSUE TITLE
Fuel doesnt sync between players

### ISSUE THREAD

**Issue by SnooperSwiper** [overextended/ox_fuel#15]
One way to replicate is to have a person fuel a vehicle with a jerry can, when the person who refueled the car gets into the car they will have the new fuel level however the other person will have a different fuel level

**Comment by PoorLatency** [comment]
Can confirm, one person sees another fuel than the other. So, for an example let's say there's two of you in a car, driver sees 20% fuel, but the passenger sees 100% fuel. Therefore, they swap seats and car will have 100% fuel.

**Comment by thelindat** [comment]
I guess still waiting for the PR to allow the client to instantiate statebags.

Easiest fix is to send a server event if the entity has no fuel value.

**Comment by thelindat** [comment]
Statebag is now created on the server.
