### ISSUE TITLE
Issue: Fueling

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_fuel#28]
You're able to get infinite gas for free by doing the following;

1. Re-fuel your car.
2. When refueling, drop your money out of the inventory.
3. After the fuel completes, pick your money up.
4. Easy free gas!

**Comment by LukeWasTakenn** [comment]
Is the inventory accessible even then fueling? I swear this was fixed before 🤔

**Comment by PoorLatency** [comment]
> Is the inventory accessible even then fueling? I swear this was fixed before 🤔

Yes.

**Comment by LukeWasTakenn** [comment]
This issue was possibly solved in the latest version of ox_lib so please try updating and see whether the issue is still occuring.

**Comment by PoorLatency** [comment]
> This issue was possibly solved in the latest version of ox_lib so please try updating and see whether the issue is still occuring.

Will try today.
