### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by DonJoan** [overextended/ox_fuel#29]
![image](https://user-images.githubusercontent.com/71422908/169701179-c0f84002-f756-4aee-98c1-9495dc998599.png)

**Comment by LukeWasTakenn** [comment]
Any way to consistently replicate this issue? An error message in this context doesn't mean much, at all.

**Comment by DonJoan** [comment]
When I get into a vehicle

**Comment by BaspelOp** [comment]
Yes, i have same problem. When i get into a vehicle.

**Comment by edecadt** [comment]
I got this issue with bmx

**Comment by ohitsjudd** [comment]
I can confirm this as well. Error happens upon entering a vehicle.

**Comment by juddisjudd** [comment]
I can confirm this as well. Error happens upon entering a vehicle for the first time only. (tested with non owned cars only)

Placing `print(state.fuel)` on line 56 in client.lua shows first enter of car state.fuel is nil (cause of error)
Entering car again, no error and print will tell you how much fuel you have.

**Comment by juddisjudd** [comment]
**UPDATE:**
Pulling latest commits resolves this issue. 1.0.0 release produces error.
