### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LukeWasTakenn** [overextended/ox_fuel#30]
- [ ] Differentiate gas powered vehicles to electric ones
- [ ] Support ESX*
- [ ] Support QBCore*

*Support for frameworks is currently awaiting a change to ox_lib which would make checking for money and items possible to easily integrate the frameworks.

**Comment by juddisjudd** [comment]
Notes for electric cars.

In vehicles.meta cars can have the following flag but does not actually do anything for consumption/need for gas.
Enum: 43 
Name: FLAG_IS_ELECTRIC

Not sure if we can have a check for this flag then we "mark" car as electric and not needing gas.

Alternative and a bit more simplistic would be, set with config and function something like:
```lua
Config.VehicleNames = { 
	'tesla' 
}
```

```lua
function IsEV(name)
    for _, evName in ipairs(Config.VehicleNames) do
        if name == evName then
            return true
        end
    end
    return false
end
```
[Source/Ref](https://github.com/wtf-fivem-mods/wtf_ev)
