### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Burx12** [overextended/ox_fuel#35]
Theres a bug where you can fuel your can anywhere any time 

![image](https://user-images.githubusercontent.com/107647166/178307707-9e3747ea-f445-4ee7-b100-d876e321ebd7.png)

**Comment by LukeWasTakenn** [comment]
Thank you for providing 0 information about the actual issue.

**Comment by Burx12** [comment]
thats the bug you can refuel your gas can any where it doens't matter no error nothing its like its meant to be like this

**Comment by Burx12** [comment]
a
