### ISSUE TITLE
Fueling with gas can will lock other keys after fueling

### ISSUE THREAD

**Issue by Luadih** [overextended/ox_fuel#42]
For some reason if I fuel any car with the gas can or even refuel the gas can it locks up the key for aiming and entering a vehicle.
This doesn't happen while refueling with the stations

This happens with latest ox_lib and ox_inventory.

**Comment by thelindat** [comment]
@Luadih Let me know if that resolved it for you.

**Comment by Luadih** [comment]
That resolved it, Thank you
