### ISSUE TITLE
Q target issue? only works when restarting the source. apon restart of the server q target does not work.

### ISSUE THREAD

**Issue by gunna2x** [overextended/ox_fuel#54]
im not to sure but when using "q-target"
witch says this ox_fuel supports
i only get the q target menu to pop up when restarting the resource.
fresh off a restart the q target does not work
![lol](https://user-images.githubusercontent.com/117485880/200076762-b947800d-a102-437d-8561-d9c3fefd40d7.PNG)

**Comment by LukeWasTakenn** [comment]
Wrong load order
