### ISSUE TITLE
fuel level at 65

### ISSUE THREAD

**Issue by deputystrand** [overextended/ox_fuel#67]
everytime i take a vehicle out from the garage the fuel level will be 65
before saving the vehicle back in to the garage no matter your fuel is below or above 65  once you save the vehicle and take out the vehicle from the garage the 1st second is showing you the correct value but then after that it will turn back to 65

been checking the native on es extended / ox lib is either getvehiclefuellevel or setvehiclefuellevel
garage script using is luke garage script and there is no fuel native in the luke garage script

would hope to get this issue fix...
beside the above issue the script is working just fine...

**Comment by thelindat** [comment]
If it's 65 _every single time_ then something is setting it to 65.

**Comment by deputystrand** [comment]
issue havent solve and u close the post for??
2ndly i think your script having the bug for that
cause i tried legacy fuel and legacy fuel work perfectly... if your fuel level is 50 and you save in the garage and take back out you will get 50
so i hope you can really look into you script and help user out and not close the post plus reply saying 'there is something setting it to 65'.. cause because i open the post i check everything
