### ISSUE TITLE
[SUGGESTION] Payments choose

### ISSUE THREAD

**Issue by Gameadictive** [overextended/ox_fuel#69]
I would be perfect to when u fuel or buy a can to choose payment method.

**Comment by KabanosDevelopment** [comment]
Awesome idea!

**Comment by thelindat** [comment]
I made a fucking update so you can easily redefine the payment method and you post this nonsense. Look at the readme, even.

**Comment by Gameadictive** [comment]
Yeah im reading but i dont know how to do it.
