### ISSUE TITLE
Error when fueling without money in QBCore

### ISSUE THREAD

**Issue by onscripts** [overextended/ox_fuel#71]
![image](https://user-images.githubusercontent.com/94694368/232319338-af77001c-2c9a-4e0b-ba90-7ada8b791b58.png)
This only happens when you don't have money in the inventory and try to fuel, you get the progress bar but it isn't fueling anything

**Comment by thelindat** [comment]
If you don't have money then the money count is 0, and you won't start fuelling; even if the "money" item doesn't exist it will return 0.

No situation is leading to this error, and you have included no information.
