### ISSUE TITLE
Less Fuel problem

### ISSUE THREAD

**Issue by ynnniV** [overextended/ox_fuel#79]
Hi,
Just noticed a days ago a strage action from the car when i've like 0/1% of fuel into it. When i try to accellerate the car is going back and not stopped where she need to stay or like shutdown the car. I'll give you a video below.

How can i fix it?

Video: https://streamable.com/djkop8

**Comment by thelindat** [comment]
That's standard game behaviour from like ~4% fuel (getting worse and worse as it lowers).
