### ISSUE TITLE
ox Fuel not start

### ISSUE THREAD

**Issue by JeffreyKroonenberg** [overextended/ox_fuel#89]
ox fuel does not want to start automatically, we have to do this manually

**Comment by xrtw** [comment]
> ox fuel does not want to start automatically, we have to do this manually

start it after ox_inventory then :?

**Comment by JeffreyKroonenberg** [comment]
Yes, it starts after ox_inventory.

**Comment by Saksen2k1** [comment]
did we found a solution here for sitting even with the problem

**Comment by Nikwitz** [comment]
You need to ensure ox_target before ox_fuel.

**Comment by swiift13** [comment]
> You need to ensure ox_target before ox_fuel.

this is a solution. ty a lot <3
